import Head from "next/head";
import Nextimage from "./components/Nextimage";
import Cloudinary from "./components/Cloudinary";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Nextimage />
      <Cloudinary />
      </main>
    </div>
  );
}
